apiVersion: v1
kind: Service
metadata:
  name: iperf-server-service
spec:
  selector:
    app: iperf-server   # Assuming you have a label "app: iperf-server" on your iperf-server pod
  ports:
    - protocol: TCP
      port: 5201        # Port that your iperf-server is listening on
