apiVersion: v1
kind: Pod
metadata:
  name: emulator
spec:
  containers:
  - name: stress-container
    image: emulator:1.0
    command: ["stress-ng"]
    args: ["--cpu", "$(CPU_WORKERS)", "--cpu-load", "$(CPU_LOAD)", "--vm", "$(VM_WORKERS)", "--vm-bytes", "$(VM_BYTES)", "--timeout", "$(DURATION_IN_SECONDS)"]
    env:
      - name: CPU_WORKERS
        valueFrom:
          configMapKeyRef:
            name: stress-ng-config
            key: CPU_WORKERS
      - name: CPU_LOAD
        valueFrom:
          configMapKeyRef:
            name: stress-ng-config
            key: CPU_LOAD
      - name: VM_WORKERS
        valueFrom:
          configMapKeyRef:
            name: stress-ng-config
            key: VM_WORKERS
      - name: VM_BYTES
        valueFrom:
          configMapKeyRef:
            name: stress-ng-config
            key: VM_BYTES
      - name: DURATION_IN_SECONDS
        valueFrom:
          configMapKeyRef:
            name: stress-ng-config
            key: DURATION_IN_SECONDS

  - name: iperf-client
    image: networkstatic/iperf3
    command: ["iperf3"]
    args: ["-c", "10.1.0.14", "-p", "5201", "-t", "$(DURATION_IN_SECONDS)", "-b", "$(BANDWIDTH)", "-i", "$(CLIENT_COUNT)"]
    env:
      - name: DURATION_IN_SECONDS
        valueFrom:
          configMapKeyRef:
            name: iperf-config
            key: DURATION_IN_SECONDS
      - name: BANDWIDTH
        valueFrom:
          configMapKeyRef:
            name: iperf-config
            key: BANDWIDTH
      - name: CLIENT_COUNT
        valueFrom:
          configMapKeyRef:
            name: iperf-config
            key: CLIENT_COUNT

  restartPolicy: Never
